import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CartService } from 'src/app/service/cart.service';
import { ProductService } from 'src/app/service/product.service';

@Component({
  selector: 'app-carnage',
  templateUrl: './carnage.component.html',
  styleUrls: ['./carnage.component.css']
})
export class CarnageComponent implements OnInit {
  products: any[] = [];
  apiBaseUrl: string = 'http://localhost:8080';
  userId: string = 'yourUserId'; // Replace 'yourUserId' with the actual user ID

  constructor(private router: Router, private cartService: CartService, private productService: ProductService, private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchProducts();
  }

  fetchProducts() {
    this.productService.getAllProducts().subscribe((response: any) => {
      this.products = response.map((product: any) => ({
        ...product,
        showReview: false, // Initialize showReview flag to false
        review: { stars: 0, comment: '' } // Object to store review data
      }));
    });
  }

  addToCart(product: any) {
    // Add item to the cart
    this.cartService.addItem(product);
  }

  goToCart(product: any) {
    // Add item to the cart
    this.cartService.addItem(product);

    // Navigate to the cart component
    this.router.navigate(['/cart']);
  }

  toggleReview(product: any) {
    product.showReview = !product.showReview; // Toggle the showReview flag
  }

  cancelReview(product: any) {
    product.showReview = false; // Hide the review form
    // You can also reset the review object here if needed
  }

  submitReview(product: any) {
    // Submit review to the API
    const url = `${this.apiBaseUrl}/api/v1/products/feed-back/${this.userId}/${product.id}`;
    const payload = {
      id: 0, // The ID should be generated by the backend
      productId: product.id,
      userId: this.userId,
      stars: product.review.stars,
      comment: product.review.comment
    };
    this.http.post(url, payload).subscribe(() => {
      console.log('Review submitted successfully');
      // Reset the review object after submission
      product.review = { stars: 0, comment: '' };
    }, error => {
      console.error('Failed to submit review', error);
      // Handle error
    });
}
}